### ISSUE TITLE
libs not loaded

### ISSUE THREAD

**Issue by peacedove** [marijnh/tern_for_vim#104]
the TernDef, autocomplete works, but when I create a .tern-project file and try to load the jquery definition, nothing happened. 

My directory is like this
- root/
    - js/
       - aaa.js
       - bbb.js
    - tern-project

the tern-project is under the root folder

and my .tern-project file looks like this

```
{
    "libs": [
        "jquery"
    ],
    
    "plugins": {
    }
}

**Comment by marijnh** [comment]
When you say 'nothing happens', do you mean Tern stops working entirely, or do the jQuery completions not work? You should probably also include the browser definitions, since jQuery uses those. Other than that, I don't know what could be happening, and would need more information to be able to say anything useful.

**Comment by peacedove** [comment]
Only the jQuery completions doesn't work. When you said include the browser definitions, does that means I should add "browser" in the "libs" field? I tried and made the .tern-project file like this but the jQuery completions are still not working.

```
{
    "libs": [
        "browser",
        "jquery"
    ],

    "plugins": {
    }
}

**Comment by marijnh** [comment]
Can you give a concrete example of a file where you'd expect a completion but aren't getting one?

**Comment by peacedove** [comment]
For example
```
$(document).rea
```
should see ready shows up, but it does not.

<img width="1785" alt="screen shot 2015-09-03 at 11 50 47 pm" src="https://cloud.githubusercontent.com/assets/1399376/9676249/cdc68bb0-5296-11e5-9a6d-f64be565111c.png">

**Comment by peacedove** [comment]
It turns out that I have some settings in my .vimrc prevent tern_for_vim to work properly. It works properly after I remove those settings.

[Related URL](http://vi.stackexchange.com/questions/2495/ternjs-plugin-is-not-working-as-expected)

**Comment by marijnh** [comment]
Oh, that's odd. Thanks for the update.
