### ISSUE TITLE
Lint with tern & vim

### ISSUE THREAD

**Issue by angelozerr** [marijnh/tern_for_vim#105]
CodeMirror, Eclipse, Emacs and Atom have implemented marker to support JavaScript validation (static type checker like http://flowtype.org/) with [tern-lint](https://github.com/angelozerr/tern-lint) . If you are interested you could implement marker with vim to use the tern plugin lint.

Don't hesitate to contact me if you need some info about the tern lint.

**Comment by marijnh** [comment]
I know you're doing a Tern linter, and that's great, but I really don't want to get involved with that.
