### ISSUE TITLE
TernError: No type found at the given position.

### ISSUE THREAD

**Issue by oblitum** [marijnh/tern_for_vim#107]
I'm getting this message frequently when the cursor is in some blank line or any random place. Couldn't it be muted or a less noisy mode be provided?

**Comment by marijnh** [comment]
Are you using any tern command when this happens? If so, which one?

**Comment by oblitum** [comment]
@marijnh I'm not, it comes from normal code completion:

```vim
let g:tern_show_signature_in_pum = 1
let g:tern_show_argument_hints = 'on_move'
```

**Comment by marijnh** [comment]
Ugh, it looks like whoever added argument hinting didn't think to also add a silent request mode, and indeed, if you turn on automatic argument hints you're constantly seeing errors. Attached patch should help.

**Comment by oblitum** [comment]
Many thanks, it's clean now.
