### ISSUE TITLE
Tern interfering with syntastic?

### ISSUE THREAD

**Issue by lfilho** [marijnh/tern_for_vim#108]
Hello there. Thanks for you awesome project!

I've just installed it but I'm not sure if I've done something wrong: after installing it, I've opened a JS file, delete a random `}`, saved the file and it didn't report the expected error.

1. Does it suppress the need of syntastic plugin? I.e: does it provide syntax checking too?
2. If not, what's going on for my file not being linted anymore?
3. Is it mandatory to have a `.tern-project` file? I didn't create one (yet) but I assume the basics would work without a `.tern-project` file?

Thanks

**Comment by marijnh** [comment]
Tern does not do any kind of syntax checking. I don't know how it might interact with Syntastic, I am under the impression that the way Tern is implemented shouldn't cause any conflicts, but I don't know enough about vim scripting to give you a deeper diagnosis.

**Comment by lfilho** [comment]
Weird. I didn't have much time to keep poking around with it so I just deleted tern/tern for vim, and then it started working again... Thanks anyways for your help!
