### ISSUE TITLE
Installed module names completion

### ISSUE THREAD

**Issue by dan-silva** [marijnh/tern_for_vim#111]
Is it possible to have in the `require('` the omnicompletion for modules installed in `node_modules`? 

Currently it appears that only the definitions at `node` plugin are shown, and `node_resolve` plugin doesn't seem to make any difference in this situation (I'm not even sure if this plugin intends to solve this, the docs don't say much).

**Comment by marijnh** [comment]
Not without us reproducing a big part of Node's module resolution algorithm, which I am not really interested in doing.

**Comment by dan-silva** [comment]
And what about a simple lookup in the `node_modules` directory? This is the approach that [this fork of vim-nodejs-complete](https://github.com/ahayman/vim-nodejs-complete) uses. Or maybe parsing the `package.json` file and look for `dependencies`, `peerDependencies` and `devDependencies`, as these names are the same for module names.

**Comment by marijnh** [comment]
Scanning `package.json` is a clever and relatively simple idea to implement. Patch https://github.com/marijnh/tern/commit/13a5528b6620c3ed82156366d5b2306e1ccb9dd9 does this.

**Comment by dan-silva** [comment]
Wow, nice! Thank you.

Just to note, the `package.json` will only be parsed if there's a `.tern-project` file at the root of the project. As I was using a default `.tern-project` in my $HOME for almost all projects, it wasn't detecting my `package.json` file until I added it.

I don't know if this is the intended behavior (a project **always** being detected where `.tern-project` is present), but maybe it would make more sense to look at the `npm root` parent directory in this case, as using a "global" `.tern-project` shouldn't represent the project path.

Or maybe there could be a flag like `"global": true`, so if no `.tern-project` on the parent directories without this flag is found it would fallback to the `npm root` parent as the project root.

NOTE: The `npm root` command was the only way I found to find something near project root. Obviously looking for the presence of a `package.json` in the parent directories would make more sense (or multiple `package.json`s, I don't know what is the behavior of nested projects).

**Comment by marijnh** [comment]
I don't see this failing when I don't have a `.tern-project` file. In that case, the project dir will default to the current directory, and the `node_resolve` plugin scans upwards from there, so it should be able to find your `package.json` anyway.
