### ISSUE TITLE
TernDef command to go directly to the source

### ISSUE THREAD

**Issue by dani-h** [marijnh/tern_for_vim#113]
If I have a file structure as such:

File foo.js
```javascript
function foo() {}

module.exports = {
  foo: foo
};
```

File bar.js
```javascript
var foo = require('foo')
foo.foo // call :TernDef here brings you to module.exports.foo instead of the source
```

Is it possible to go to the source function declaration instead of module.exports?

**Comment by dani-h** [comment]
On top of this,

If module.exports are defined using the shorthand literal, tern can't find the original function

```javascript
function foo() {}
module.exports = {
  foo
}
```

**Comment by marijnh** [comment]
Nope, this isn't possible. Tern will take you to where the property you are looking at is defined. This is usually the right place, but as you found, sometimes it isn't optimal. Still, I am not aware of a good way to distinguish between these two types of situations.
