### ISSUE TITLE
.vimrc libs and plugin global settins

### ISSUE THREAD

**Issue by franleplant** [marijnh/tern_for_vim#84]
Hi!
    Thanks for Tern and it's vim plugin! They are awesome.

I'd like to set in my `.vimrc` a base set of plugins and libs that I want to be enable by default in every project, is there a way of doing this?

Thanks!

**Comment by marijnh** [comment]
Nope, but you can create a `~/.tern-config` file to do this (which has the same format as `.tern-project` files).

**Comment by franleplant** [comment]
Wow this is really great! I didn't saw it in the docs, maybe it's missing.

Thanks!
Fran
