### ISSUE TITLE
Compatibility with NeoVim

### ISSUE THREAD

**Issue by alem0lars** [marijnh/tern_for_vim#87]
I'm using `tern_for_vim` with NeoVim.

When I try to save a coffeescript file I get the following error:
```
Error detected while processing function provider#python#Call:
line    1:
NvimError('Vim:E121: Undefined variable: b:ternBufferSentAt',)
```

**Comment by myshov** [comment]
You need to talk about this issue developers of neovim.

**Comment by marijnh** [comment]
I agree with @myshov . I'm already way out of my comfort zone testing on regular Vim -- I don't volunteer to also start debugging issues in NeoVim.
