### ISSUE TITLE
Tern with Typescript's __extends

### ISSUE THREAD

**Issue by davidsteinberger** [marijnh/tern_for_vim#93]
*Typescript* when compiled to js uses an *__extends* function like below to copy the properties from the base class. Is it possible for tern to understand that *__extends* function and get completion for base class properties?

    var __extends = this.__extends || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        __.prototype = b.prototype;
        d.prototype = new __();
    };

**Comment by marijnh** [comment]
Doesn't it already? I just did a simple test and everything looked fine. This is almost exactly the same inheritance shim as the one used by CoffeeScript, support for which is tested by the test suite.

Please give me a (minimal) piece of code that uses this, and describe what goes wrong.

**Comment by davidsteinberger** [comment]
Thanks for the fast reply. I just tried to reproduce it in a clean backbone-amd + ts app and it works indeed. Must be something else in my setup.
