### ISSUE TITLE
Connect to running tern server

### ISSUE THREAD

**Issue by davidsteinberger** [marijnh/tern_for_vim#94]
This is not really an issue, more a question. I'm having some issues with the completion (unable to reproduce) and would like tern_for_vim to connect to a running server (running with --verbose). How can I make *tern_for_vim* connect instead of starting a new server?

**Comment by marijnh** [comment]
If you run the server in your project dir (the dir where `.tern-project` lives), it will create a `.tern-port` file there, and if you start using `tern_for_vim` on that project, it should automatically connect to the running server (might need to kill existing servers first, if you already had files in that project open).

**Comment by mattsawyer77** [comment]
I'm trying to accomplish this as well. I'm running a standalone tern server and then launching vim (nvim in my case, not sure if that matters?) from the same directory that contains the .tern-port file. I can see that tern works within a nvim session. But if I exit nvim and reopen it, it seems my tern cache has been cleared completely. But maybe I'm understanding how this is supposed to work.

**Comment by marijnh** [comment]
Is the file that you're editing also in that same directory? Tern_for_vim will look for a `.tern-port` file in what it considers the "project directory" of the file you're editing -- the nearest enclosing directory with a `.tern-project` file, or failing that, the script file's directory itself.
