### ISSUE TITLE
Not loading?

### ISSUE THREAD

**Issue by bensaufley** [marijnh/tern_for_vim#95]
I give up. I can't find anything on StackOverflow (or even where to start), and I can't find any errors or hints about what else it could be, so I'm coming here: I'm using Pathogen and have cloned this git right next to all my other packages, but it doesn't seem to do anything.

- I have `tern` npm-installed globally.
- I've run `npm install` in the local copy's root – that behaved as I'd expect, and running `npm list` in that directory spits out `tern_for_vim@0.5.0` and its subordinate tree.
- Running `tern` from zsh runs tern as I'd expect.
- Running `node ~/.vim_runtimes/sources_non_forked/tern_for_vim/node_modules/tern/bin/tern --no-port-file` works too. (`.vim_runtimes` is where all my plugins are – using [this setup](https://github.com/amix/vimrc) – and I inferred that path above from `../node_modules/tern/bin/tern` in [L15 of autoload/tern.vim](https://github.com/marijnh/tern_for_vim/blob/master/autoload/tern.vim#L15))
- I tried to get this working out of hope of using it with [tern-meteor](https://github.com/Slava/tern-meteor), and as such I'm using the `.tern-project` file suggested therein.
- Opening `vim` and typing `:TernDef` or another one of its commands in a JS file returns: `Not an editor command`. I have no other indication that Tern is trying to start a server, or run, or affect VIM in any way.

What am I missing here? Does it have something to do with `.vim_runtimes` vs `.vim`?

**Comment by marijnh** [comment]
The description of your symptoms suggests that vim is not loading the plugin. Do you have python enabled in your vim? Anything suspicious showing up in `:messages`?

**Comment by bensaufley** [comment]
`vim version` lists `+python`, which I take to mean python is enabled. Running `:messages` from vim only shows `Messages maintainer: Bram Moolenaar <Bram@vim.org>`. It doesn't appear that I can scroll through anything there for more info…

**Comment by marijnh** [comment]
Then Pathogen is somehow not finding the plugin. I have very little experience with vim and pathogen myself, so I don't know what could cause that. Re-check your directory structure, maybe.

**Comment by bensaufley** [comment]
Thanks for your help. Tried doing exactly the same setup on a second computer and Tern loaded fine. It turns out the difference was that my `.vimrc` wasn't actually referencing the .vim file that ran the Pathogen stuff. I'm not 100% sure why other pathogen stuff was loading. I've now got it running smoothly on this computer.
