### ISSUE TITLE
TernDef can not jump correctly from within a JSON object. 

### ISSUE THREAD

**Issue by larryhe** [marijnh/tern_for_vim#96]
I am not sure if this is a Tern issue or a tern_for_vim plugin issue. In below code snippet, If you run TernDef from this.fun1() line (cursor is under fun1), You will get no definition found. Any clue for this? Thanks. 
var obj = {
fun1: function(){
     console.log("fun1 is running");
}, 
fun2: function(){
     this.fun1();   //this line, you run TernDef command
}
}

**Comment by marijnh** [comment]
Attached Tern patch should help (you'll have to manually update Tern from git to get it, though)
